version: "2"
run:
  timeout: 10m
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/ovechkin-dm/mockio)
        - blank
        - dot
        - alias
