site_name: mockio
site_url: https://ovechkin-dm.github.io/mockio/
site_description: >-
  Mock library for Go

repo_name: ovechkin-dm/mockio
repo_url: https://github.com/ovechkin-dm/mockio

theme:
  name: material
  icon:
    logo: fontawesome/brands/golang
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - toc.follow
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true


nav:
  - Home: index.md
  - Quick start: quick-start.md
  - Features:
      - Configuration: features/configuration.md
      - Matchers: features/matchers.md
      - Method stubbing: features/method-stubbing.md
      - Argument captors: features/captors.md
      - Error reporting: features/error-reporting.md
      - Verification: features/verification.md
      - Parallel execution: features/parallel-execution.md
      - Limitations: features/limitations.md
  - Examples:
      - Custom matcher: examples/custom-matcher.md
      - Mock within a mock: examples/mock-within-mock.md
      - Mocking void method: examples/mocking-void-method.md


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

plugins:
  - glightbox
  - mike:
      alias_type: symlink
      canonical_version: latest
  - open-in-new-tab
  - search
  - social